name: merchandiser_clone
description: "Merchadising Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  faker: ^2.1.0
  # qr_code_scanner: ^1.0.1
  provider: ^6.1.1
  badges: ^3.1.2
  intl: ^0.19.0
  dynamic_height_grid_view: ^0.0.4
  persistent_bottom_nav_bar: ^5.0.2
  collection: ^1.17.2
  fluttertoast: ^8.2.4
  sticky_headers: ^0.3.0+2
  flutter_easyloading: ^3.0.5
  http: ^1.1.0
  super_banners: ^0.0.1
  flutter_screenutil: ^5.9.0
  # flutter_typeahead: ^4.8.0
  another_flushbar: ^1.12.30
  # flutter_keyboard_visibility: ^5.0.0
  # win32: ^5.5.4  # Uncomment if needed
  mobile_scanner: ^6.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # (your version mentioned 5.0.0 but latest flutter_lints is 3.0.0)

flutter:
  uses-material-design: true

  assets:
    - assets/
